### DISCUSSION TITLE
Color Themes for Eclipse Integration

### DISCUSSION THREAD

**Discussion by rsoika** [eclipse-glsp/glsp#1366] [Q&A] [answered]
Hi,
I have a general question regarding the GLSP Eclipse Integration.
In Theia and VS-Code we can use the color schemas provided by the IDEs. For example you can define a background color like 

```css
.bpmn-properties-body .categorization-detail button:hover {
    background-color: var(--theia-button-hoverBackground);
}
```

or for vscode

```css
.bpmn-properties-body .categorization-detail button:hover {
    background-color: var(--vscode-button-hoverBackground);
}
```

I wonder if such a concept is also available for Eclipse? At least I did not find something like that.
