### ISSUE TITLE
Wrong color schema in Toolbar

### ISSUE THREAD

**Issue by rsoika** [eclipse-glsp/glsp#946]
I think there is a wrong color schema in the GLSP Toolbar.

The Backgound color of the `group-header` is set to `--theia-activityBar-background`

In the Theme "Light (Visual Studio)" this color is a dark black and so the group headers are not readable:

![image](https://user-images.githubusercontent.com/1339124/222905687-34710793-492f-4bf6-96f7-e23e0731670b.png)

I think in the `tool-pallette.css` the `.tool-palette .palette-body .group-header`  should be set to 

```css
.tool-palette .palette-body .group-header {
  ...
    background: var(--theia-sideBar-background);
 ...
}
```
This works well for all themes
